"""create_platform_tables

Revision ID: 0002_create_platform_tables
Revises: 0001_enable_vector_extension
Create Date: 2026-05-30 10:52:43.845049
"""

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

try:
    from pgvector.sqlalchemy import Vector
except ImportError:

    class Vector(sa.types.UserDefinedType):
        cache_ok = True

        def __init__(self, dimensions: int) -> None:
            self.dimensions = dimensions

        def get_col_spec(self, **kw: object) -> str:
            return f"VECTOR({self.dimensions})"


# revision identifiers, used by Alembic.
revision = "0002_create_platform_tables"
down_revision = "0001_enable_vector_extension"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "accounts",
        sa.Column(
            "account_id",
            sa.UUID(),
            server_default=sa.text("gen_random_uuid()"),
            nullable=False,
        ),
        sa.Column("firebase_uid", sa.Text(), nullable=False),
        sa.Column("email", sa.Text(), nullable=True),
        sa.Column("display_name", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("last_seen_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("account_id"),
        sa.UniqueConstraint("firebase_uid"),
    )
    op.create_table(
        "characters",
        sa.Column(
            "character_id",
            sa.UUID(),
            server_default=sa.text("gen_random_uuid()"),
            nullable=False,
        ),
        sa.Column(
            "behavior_profile",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column("embedding", Vector(1536), nullable=True),
        sa.PrimaryKeyConstraint("character_id"),
    )
    op.create_table(
        "sessions",
        sa.Column(
            "session_id",
            sa.UUID(),
            server_default=sa.text("gen_random_uuid()"),
            nullable=False,
        ),
        sa.Column("arc_id", sa.Text(), nullable=False),
        sa.Column("status", sa.Text(), nullable=False),
        sa.Column("host_account_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("current_beat_id", sa.Text(), nullable=False),
        sa.Column("quality_tier", sa.Text(), nullable=False),
        sa.Column("player_count", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["host_account_id"],
            ["accounts.account_id"],
        ),
        sa.PrimaryKeyConstraint("session_id"),
    )
    op.create_table(
        "arc_beat_states",
        sa.Column(
            "state_id",
            sa.UUID(),
            server_default=sa.text("gen_random_uuid()"),
            nullable=False,
        ),
        sa.Column("session_id", sa.UUID(), nullable=False),
        sa.Column("beat_id", sa.Text(), nullable=False),
        sa.Column(
            "statemachine_config",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=False,
        ),
        sa.Column(
            "transition_history",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'[]'::jsonb"),
            nullable=False,
        ),
        sa.Column(
            "snapshot_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "is_current", sa.Boolean(), server_default=sa.text("true"), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["session_id"],
            ["sessions.session_id"],
        ),
        sa.PrimaryKeyConstraint("state_id"),
    )
    op.create_index(
        "ix_arc_beat_states_session_id_is_current",
        "arc_beat_states",
        ["session_id", "is_current"],
        unique=False,
    )
    op.create_table(
        "consent_records",
        sa.Column(
            "consent_id",
            sa.UUID(),
            server_default=sa.text("gen_random_uuid()"),
            nullable=False,
        ),
        sa.Column("account_id", sa.UUID(), nullable=True),
        sa.Column("session_id", sa.UUID(), nullable=True),
        sa.Column("consent_type", sa.Text(), nullable=False),
        sa.Column("granted", sa.Boolean(), nullable=False),
        sa.Column(
            "granted_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("consent_version", sa.Text(), nullable=False),
        sa.ForeignKeyConstraint(
            ["account_id"],
            ["accounts.account_id"],
        ),
        sa.ForeignKeyConstraint(
            ["session_id"],
            ["sessions.session_id"],
        ),
        sa.PrimaryKeyConstraint("consent_id"),
    )
    op.create_table(
        "decision_logs",
        sa.Column(
            "decision_id",
            sa.UUID(),
            server_default=sa.text("gen_random_uuid()"),
            nullable=False,
        ),
        sa.Column("session_id", sa.UUID(), nullable=False),
        sa.Column(
            "timestamp",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("decision_type", sa.Text(), nullable=False),
        sa.Column(
            "input_context", postgresql.JSONB(astext_type=sa.Text()), nullable=False
        ),
        sa.Column("outcome", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.ForeignKeyConstraint(
            ["session_id"],
            ["sessions.session_id"],
        ),
        sa.PrimaryKeyConstraint("decision_id"),
    )
    op.create_table(
        "decisions",
        sa.Column(
            "decision_id",
            sa.UUID(),
            server_default=sa.text("gen_random_uuid()"),
            nullable=False,
        ),
        sa.Column("session_id", sa.UUID(), nullable=False),
        sa.Column(
            "timestamp",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("decision_type", sa.Text(), nullable=False),
        sa.Column(
            "context",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column(
            "outcome",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["session_id"],
            ["sessions.session_id"],
        ),
        sa.PrimaryKeyConstraint("decision_id"),
    )
    op.create_table(
        "events",
        sa.Column(
            "event_id",
            sa.UUID(),
            server_default=sa.text("gen_random_uuid()"),
            nullable=False,
        ),
        sa.Column("session_id", sa.UUID(), nullable=False),
        sa.Column(
            "timestamp",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("actor_char_id", sa.UUID(), nullable=True),
        sa.Column("event_type", sa.Text(), nullable=False),
        sa.Column(
            "payload",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column("content_text", sa.Text(), nullable=True),
        sa.Column("embedding", Vector(1536), nullable=True),
        sa.ForeignKeyConstraint(
            ["actor_char_id"],
            ["characters.character_id"],
        ),
        sa.ForeignKeyConstraint(
            ["session_id"],
            ["sessions.session_id"],
        ),
        sa.PrimaryKeyConstraint("event_id"),
        comment="Append-only table. Enforcement lives at the engine layer.",
    )
    op.create_index(
        "ix_events_event_type_timestamp",
        "events",
        ["event_type", "timestamp"],
        unique=False,
    )
    op.create_index(
        "ix_events_session_id_timestamp",
        "events",
        ["session_id", "timestamp"],
        unique=False,
    )
    op.create_table(
        "facts",
        sa.Column(
            "fact_id",
            sa.UUID(),
            server_default=sa.text("gen_random_uuid()"),
            nullable=False,
        ),
        sa.Column("session_id", sa.UUID(), nullable=False),
        sa.Column("fact_type", sa.Text(), nullable=False),
        sa.Column(
            "fact_content", postgresql.JSONB(astext_type=sa.Text()), nullable=False
        ),
        sa.Column("embedding", Vector(1536), nullable=True),
        sa.ForeignKeyConstraint(
            ["session_id"],
            ["sessions.session_id"],
        ),
        sa.PrimaryKeyConstraint("fact_id"),
    )
    op.create_table(
        "generation_logs",
        sa.Column(
            "log_id",
            sa.UUID(),
            server_default=sa.text("gen_random_uuid()"),
            nullable=False,
        ),
        sa.Column("session_id", sa.UUID(), nullable=False),
        sa.Column(
            "timestamp",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("task_type", sa.Text(), nullable=False),
        sa.Column("quality_tier", sa.Text(), nullable=False),
        sa.Column("model_used", sa.Text(), nullable=False),
        sa.Column("latency_ms", sa.Integer(), nullable=False),
        sa.Column("input_tokens", sa.Integer(), nullable=False),
        sa.Column("output_tokens", sa.Integer(), nullable=False),
        sa.Column("cost_usd", sa.Numeric(precision=10, scale=6), nullable=False),
        sa.Column("tension_score", sa.Float(), nullable=True),
        sa.Column("prompt_text", sa.Text(), nullable=True),
        sa.Column("output_text", sa.Text(), nullable=True),
        sa.Column("prompt_embedding", Vector(1536), nullable=True),
        sa.Column("output_embedding", Vector(1536), nullable=True),
        sa.ForeignKeyConstraint(
            ["session_id"],
            ["sessions.session_id"],
        ),
        sa.PrimaryKeyConstraint("log_id"),
    )
    op.create_table(
        "locations",
        sa.Column(
            "location_id",
            sa.UUID(),
            server_default=sa.text("gen_random_uuid()"),
            nullable=False,
        ),
        sa.Column("session_id", sa.UUID(), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column(
            "metadata",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["session_id"],
            ["sessions.session_id"],
        ),
        sa.PrimaryKeyConstraint("location_id"),
    )
    op.create_table(
        "relationships",
        sa.Column(
            "relationship_id",
            sa.UUID(),
            server_default=sa.text("gen_random_uuid()"),
            nullable=False,
        ),
        sa.Column("session_id", sa.UUID(), nullable=False),
        sa.Column("source_char_id", sa.UUID(), nullable=False),
        sa.Column("target_char_id", sa.UUID(), nullable=False),
        sa.Column(
            "trust_level", sa.Float(), server_default=sa.text("0.5"), nullable=False
        ),
        sa.Column("history_tag", sa.Text(), nullable=True),
        sa.Column("current_affect", sa.Text(), nullable=True),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["session_id"],
            ["sessions.session_id"],
        ),
        sa.ForeignKeyConstraint(
            ["source_char_id"],
            ["characters.character_id"],
        ),
        sa.ForeignKeyConstraint(
            ["target_char_id"],
            ["characters.character_id"],
        ),
        sa.PrimaryKeyConstraint("relationship_id"),
        sa.UniqueConstraint(
            "session_id",
            "source_char_id",
            "target_char_id",
            name="uq_relationships_session_source_target",
        ),
    )
    op.create_table(
        "session_participants",
        sa.Column(
            "participant_id",
            sa.UUID(),
            server_default=sa.text("gen_random_uuid()"),
            nullable=False,
        ),
        sa.Column("session_id", sa.UUID(), nullable=False),
        sa.Column("character_id", sa.UUID(), nullable=False),
        sa.Column("account_id", sa.UUID(), nullable=True),
        sa.Column("join_token", sa.Text(), nullable=False),
        sa.Column("surface_type", sa.Text(), nullable=False),
        sa.Column(
            "is_ai_controlled",
            sa.Boolean(),
            server_default=sa.text("false"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["account_id"],
            ["accounts.account_id"],
        ),
        sa.ForeignKeyConstraint(
            ["character_id"],
            ["characters.character_id"],
        ),
        sa.ForeignKeyConstraint(
            ["session_id"],
            ["sessions.session_id"],
        ),
        sa.PrimaryKeyConstraint("participant_id"),
    )
    op.create_table(
        "knowledge_states",
        sa.Column(
            "ks_id",
            sa.UUID(),
            server_default=sa.text("gen_random_uuid()"),
            nullable=False,
        ),
        sa.Column("session_id", sa.UUID(), nullable=False),
        sa.Column("character_id", sa.UUID(), nullable=False),
        sa.Column("fact_id", sa.UUID(), nullable=False),
        sa.Column("source_character_id", sa.UUID(), nullable=True),
        sa.Column(
            "confidence", sa.Float(), server_default=sa.text("1.0"), nullable=False
        ),
        sa.Column(
            "provenance_chain",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'[]'::jsonb"),
            nullable=False,
        ),
        sa.Column(
            "asserted_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("superseded_by", sa.UUID(), nullable=True),
        sa.ForeignKeyConstraint(
            ["character_id"],
            ["characters.character_id"],
        ),
        sa.ForeignKeyConstraint(
            ["fact_id"],
            ["facts.fact_id"],
        ),
        sa.ForeignKeyConstraint(
            ["session_id"],
            ["sessions.session_id"],
        ),
        sa.ForeignKeyConstraint(
            ["source_character_id"],
            ["characters.character_id"],
        ),
        sa.PrimaryKeyConstraint("ks_id"),
    )
    op.create_foreign_key(
        "fk_knowledge_states_superseded_by",
        "knowledge_states",
        "knowledge_states",
        ["superseded_by"],
        ["ks_id"],
    )
    op.create_table(
        "objects",
        sa.Column(
            "object_id",
            sa.UUID(),
            server_default=sa.text("gen_random_uuid()"),
            nullable=False,
        ),
        sa.Column("session_id", sa.UUID(), nullable=False),
        sa.Column("location_id", sa.UUID(), nullable=True),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column(
            "metadata",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["location_id"],
            ["locations.location_id"],
        ),
        sa.ForeignKeyConstraint(
            ["session_id"],
            ["sessions.session_id"],
        ),
        sa.PrimaryKeyConstraint("object_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("objects")
    op.drop_constraint(
        "fk_knowledge_states_superseded_by",
        "knowledge_states",
        type_="foreignkey",
    )
    op.drop_table("knowledge_states")
    op.drop_table("session_participants")
    op.drop_table("relationships")
    op.drop_table("locations")
    op.drop_table("generation_logs")
    op.drop_table("facts")
    op.drop_index("ix_events_session_id_timestamp", table_name="events")
    op.drop_index("ix_events_event_type_timestamp", table_name="events")
    op.drop_table("events")
    op.drop_table("decisions")
    op.drop_table("decision_logs")
    op.drop_table("consent_records")
    op.drop_index(
        "ix_arc_beat_states_session_id_is_current", table_name="arc_beat_states"
    )
    op.drop_table("arc_beat_states")
    op.drop_table("sessions")
    op.drop_table("characters")
    op.drop_table("accounts")
    # ### end Alembic commands ###
