import {createSession,recordAction,completeSession,serializeTelemetry,buildFeedbackUrl,detectEnvironment} from './runtime.js';
const cfg=window.NIGHTCAP_PLAYTEST, app=document.querySelector('#app'), notebook=document.querySelector('#notebook'), notes=document.querySelector('#notes');
document.querySelector('#version').textContent=cfg.version.replace('nightcap-paper-test-02-','');
const KEY=`nightcap:${cfg.version}:session`; let s=load();
function load(){try{const x=JSON.parse(sessionStorage.getItem(KEY));return x?.prototypeVersion===cfg.version?x:createSession(cfg.version)}catch{return createSession(cfg.version)}}
function save(){sessionStorage.setItem(KEY,JSON.stringify(s));renderNotes()}
function restart(){sessionStorage.removeItem(KEY);s=createSession(cfg.version);save();welcome()}
function panel(inner){app.innerHTML=`<div class="panel">${inner}<div class="exit"><button id="exit-early">End test early & give feedback</button></div></div>`;document.querySelector('#exit-early')?.addEventListener('click',()=>feedback('abandoned'))}
function progress(n,total=6){return `<div class="progress">${Array.from({length:total},(_,i)=>`<span class="${i<n?'done':''}"></span>`).join('')}</div>`}
function renderNotes(){if(!s.discoveries.length){notebook.classList.add('hidden');return}notebook.classList.remove('hidden');notes.innerHTML=s.discoveries.map(x=>`<div class="note">${escapeHtml(x)}</div>`).join('')}
function escapeHtml(v){return String(v).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function welcome(){notebook.classList.add('hidden');panel(`<span class="fixture-tag">${cfg.fixtureStatus}</span><h1>${cfg.title}</h1><p class="muted">${cfg.subtitle}</p><p class="notice">${cfg.notice}</p><p class="muted">The feedback service may retain normal technical metadata such as an IP address even though this test does not ask who you are.</p><div class="actions"><button class="primary" id="start">Start prototype</button></div>`);document.querySelector('#start').onclick=()=>{s=createSession(cfg.version);s.currentStep=1;save();intro()}}
function intro(){panel(`${progress(1)}<div class="eyebrow">${cfg.intro.eyebrow}</div>${cfg.intro.body.map((p,i)=>i===1?`<h2>${p}</h2>`:`<p>${p}</p>`).join('')}<div class="card"><strong>People in the room</strong><ul class="clean">${cfg.intro.suspects.map(x=>`<li>${x}</li>`).join('')}</ul></div><p><strong>You’re the investigator.</strong> Follow what interests you. Notice what doesn’t fit.</p><div class="actions"><button class="primary" id="investigate">Investigate</button></div>`);document.querySelector('#investigate').onclick=()=>{s.currentStep=2;save();investigate()}}
function investigate(){if(s.earned.length>=3){reaction();return}const used=new Set(s.earned);const available=cfg.investigations.filter(x=>!used.has(x.id));panel(`${progress(2)}<div class="eyebrow">INVESTIGATE</div><h2>What do you do?</h2><p class="muted">Choose what interests you. You have ${Math.max(1,3-s.earned.length)} investigation move${3-s.earned.length===1?'':'s'} before the room changes.</p><div class="choice-grid two">${available.map(x=>`<button data-id="${x.id}">${x.label}</button>`).join('')}</div>`);app.querySelectorAll('[data-id]').forEach(b=>b.onclick=()=>resolveInvestigation(b.dataset.id))}
function resolveInvestigation(id){const item=cfg.investigations.find(x=>x.id===id);s.earned.push(id);recordAction(s,{label:item.label,branch:item.branch,discovery:item.discovery});save();panel(`${progress(2)}<div class="eyebrow">DISCOVERY</div><h2>${item.label}</h2><p>${item.text}</p><div class="discovery"><strong>Added to your notes:</strong><br>${item.discovery}</div><div class="actions"><button class="primary" id="next">${s.earned.length>=3?'Use what you found':'Keep investigating'}</button></div>`);document.querySelector('#next').onclick=()=>s.earned.length>=3?reaction():investigate()}
function reaction(){s.currentStep=3;save();panel(`${progress(3)}<div class="eyebrow">REACT</div><h2>${cfg.reaction.title}</h2><p>${cfg.reaction.body}</p><div class="actions">${cfg.reaction.options.map((x,i)=>`<button data-r="${i}">${x.label}</button>`).join('')}</div>`);app.querySelectorAll('[data-r]').forEach(b=>b.onclick=()=>{const x=cfg.reaction.options[+b.dataset.r];recordAction(s,{label:`React: ${x.label}`,branch:'information use'});save();panel(`${progress(3)}<h2>The room reacts</h2><p>${x.result}</p><div class="actions"><button class="primary" id="pulse">Continue</button></div>`);document.querySelector('#pulse').onclick=pulse})}
function pulse(){s.currentStep=4;save();panel(`${progress(4)}<div class="eyebrow">PARTY PULSE</div><h2>${cfg.pulse.title}</h2><p>${cfg.pulse.body}</p><p><strong>${cfg.pulse.prompt}</strong></p><div class="actions">${cfg.pulse.options.map((x,i)=>`<button data-p="${i}">${x.label}</button>`).join('')}</div><p class="muted"><small>${cfg.pulse.disclaimer}</small></p>`);app.querySelectorAll('[data-p]').forEach(b=>b.onclick=()=>{const x=cfg.pulse.options[+b.dataset.p];s.pulseResult=x.label;recordAction(s,{label:`Party pulse: ${x.label}`,branch:'party pulse',discovery:x.result});save();panel(`${progress(4)}<h2>You got it.</h2><p>${x.result}</p><p>The hallway clears. Your investigation is still intact.</p><div class="actions"><button class="primary" id="resume">Resume investigation</button></div>`);document.querySelector('#resume').onclick=resume})}
function resume(){s.currentStep=5;save();const available=cfg.investigations.filter(x=>!s.earned.includes(x.id));panel(`${progress(5)}<div class="eyebrow">HUNT AGAIN</div><h2>One more move.</h2><p>The room has changed, but your notes have not.</p><div class="choice-grid two">${available.map(x=>`<button data-id="${x.id}">${x.label}</button>`).join('')}</div>`);app.querySelectorAll('[data-id]').forEach(b=>b.onclick=()=>{const item=cfg.investigations.find(x=>x.id===b.dataset.id);s.earned.push(item.id);recordAction(s,{label:item.label,branch:item.branch,discovery:item.discovery});save();panel(`${progress(5)}<h2>${item.label}</h2><p>${item.text}</p><div class="discovery"><strong>Added to your notes:</strong><br>${item.discovery}</div><div class="actions"><button class="primary" id="commit">Last move</button></div>`);document.querySelector('#commit').onclick=commit})}
function commit(){s.currentStep=6;save();panel(`${progress(6)}<div class="eyebrow">CASE COMMITMENT</div><h2>Where are you landing?</h2><p class="muted">No essay. This is a snapshot, not a verdict.</p><p><strong>Prime suspect right now</strong></p><div class="choice-grid two" id="suspects">${cfg.commitments.suspects.map(x=>`<button data-s="${x}">${x}</button>`).join('')}</div><div id="next-thread" class="hidden"><div class="divider"></div><p><strong>What would you press next?</strong></p><div class="choice-grid two">${cfg.commitments.next.map(x=>`<button data-n="${x}">${x}</button>`).join('')}</div></div>`);app.querySelectorAll('[data-s]').forEach(b=>b.onclick=()=>{s.caseCommitment=b.dataset.s;recordAction(s,{label:`Prime suspect: ${b.dataset.s}`,branch:'case commitment'});save();document.querySelector('#suspects').classList.add('hidden');document.querySelector('#next-thread').classList.remove('hidden');app.querySelectorAll('[data-n]').forEach(n=>n.onclick=()=>{s.finalNextInterest=n.dataset.n;recordAction(s,{label:`Press next: ${n.dataset.n}`,branch:'case commitment'});save();feedback('completed')})})}
function feedback(status){completeSession(s,new Date().toISOString(),status);save();const env=detectEnvironment(navigator.userAgent,innerWidth), data=serializeTelemetry(s,env), url=buildFeedbackUrl(cfg.feedback.url,data,cfg.feedback.prefillMap);notebook.classList.add('hidden');panel(`<div class="completion"><div class="eyebrow">POST-PLAY RESEARCH</div><h2>The playable slice is over.</h2><p>Next is a short feedback survey. Your run ID is <strong>${s.runId}</strong>.</p><p class="muted">The survey is research, not more gameplay.</p><div class="actions"><a class="action primary" style="display:block;text-align:center;text-decoration:none" href="${escapeHtml(url)}">Give feedback</a><button id="restart">Restart test</button></div></div>`);document.querySelector('#exit-early')?.remove();document.querySelector('#restart').onclick=restart}
document.querySelector('#toggle-notes').onclick=()=>{const hidden=notes.classList.toggle('hidden');document.querySelector('#toggle-notes').textContent=hidden?'Show':'Hide'};
renderNotes(); if(s.completionStatus!=='in_progress' || s.currentStep===0) welcome(); else ({1:intro,2:investigate,3:reaction,4:pulse,5:resume,6:commit}[s.currentStep]||welcome)();
