"""Block edits to generated files and agent-local directories.

Emitted agents are regenerated from team-ai/; hand-editing one is silently
undone on the next emit, and CI only catches it afterwards. Blocking the write
turns a late CI failure into an immediate message.
"""

from __future__ import annotations

import fnmatch
import json
import os
import sys

BLOCKED = (
    (
        ".claude/agents/team-ai-*.md",
        "Generated from team-ai/. Edit team-ai/agents/<name>.md, then run:\n"
        "  node ../team-ai/dist/cli.js emit --target claude-code --dir team-ai "
        "--out .. --file-prefix team-ai- --no-plugin-manifest --builtin-search --allow-tracked",
    ),
    (
        "team-ai/manifest.yaml",
        "Generated by assemble-manifest. Edit team-ai/agents/manifest.fragment.yaml instead.",
    ),
)


def main() -> int:
    if os.environ.get("ARCWRIGHT_HOOK_BLOCK_GENERATED", "1") != "1":
        return 0
    try:
        payload = json.load(sys.stdin)
    except json.JSONDecodeError:
        return 0
    path = str(payload.get("tool_input", {}).get("file_path", "")).replace("\\", "/")
    if not path:
        return 0
    for pattern, message in BLOCKED:
        if fnmatch.fnmatch(path, f"*{pattern}") or fnmatch.fnmatch(path, pattern):
            print(f"Refusing to edit {path}\n{message}")
            return 2
    return 0


if __name__ == "__main__":
    sys.exit(main())
